spring:
  application:
    name: client-one
server:
  port: 20001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka,http://localhost:10002/eureka,http://localhost:10003/eureka
env:
  dev
