spring:
  application:
    name: client-one
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 20001
profiles:
  active: dev
foo: this is my foo ha!
