spring:
  application:
    name: zuul
zuul:
  routes:
    cds:
      path: /cds/**
      serviceId: CLIENT-ONE
      sensitive-headers: Cookie", "Set-Cookie", "Authorization"
server:
  port: 40001
profiles:
  active: dev

