spring:
  application:
    name: zuul
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes:
    cds:
      path: /cds/**
      serviceId: CLIENT-ONE
server:
  port: 40001
profiles:
  active: dev

